UPDATE red_producto SET foto = 'calibre-18x1-torcida.jpeg' WHERE id_mcr = 'MCR-18-1-TO-LR';
UPDATE red_producto SET foto = 'calibre-18x2-torcida.jpeg' WHERE id_mcr = 'MCR-18-2-TR-LR';
UPDATE red_producto SET foto = 'calibre-18x1-torcida.jpeg' WHERE id_mcr = 'MCR-18-1 1/2-NR-TO-LR';
UPDATE red_producto SET foto = 'calibre-18x4-torcida.jpeg' WHERE id_mcr = 'MCR-18-4-TR-LR';
UPDATE red_producto SET foto = 'calibre-18x1-torcida.jpeg' WHERE id_mcr = 'MCR-18-1-TO';
UPDATE red_producto SET foto = 'calibre-18x1-torcida.jpeg' WHERE id_mcr = 'MCR-18-1-TR';
UPDATE red_producto SET foto = 'calibre-18x1-torcida.jpeg' WHERE id_mcr = 'MCR-18-1-NR-TO';
UPDATE red_producto SET foto = 'calibre-18x1-torcida.jpeg' WHERE id_mcr = 'MCR-18-1-NR-TR';
UPDATE red_producto SET foto = 'calibre-18x1-torcida.jpeg' WHERE id_mcr = 'MCR-18-1 1/4-TO';
UPDATE red_producto SET foto = 'calibre-18x1-torcida.jpeg' WHERE id_mcr = 'MCR-18-1 1/4-TR';
UPDATE red_producto SET foto = 'calibre-18x1-torcida.jpeg' WHERE id_mcr = 'MCR-18-1 1/4-NR-TO';
UPDATE red_producto SET foto = 'calibre-18x1-torcida.jpeg' WHERE id_mcr = 'MCR-18-1 1/4-NR-TR';
UPDATE red_producto SET foto = 'calibre-18x1-torcida.jpeg' WHERE id_mcr = 'MCR-18-1 1/2-TO';
UPDATE red_producto SET foto = 'calibre-18x1-torcida.jpeg' WHERE id_mcr = 'MCR-18-1 1/2-TR';
UPDATE red_producto SET foto = 'calibre-18x1-torcida.jpeg' WHERE id_mcr = 'MCR-18-1 1/2-NR-TO';
UPDATE red_producto SET foto = 'calibre-18x1-torcida.jpeg' WHERE id_mcr = 'MCR-18-1 1/2-NR-TR';
UPDATE red_producto SET foto = 'calibre-18x1-torcida.jpeg' WHERE id_mcr = 'MCR-18-1 3/4-TO';
UPDATE red_producto SET foto = 'calibre-18x1-torcida.jpeg' WHERE id_mcr = 'MCR-18-1 3/4-TR';
UPDATE red_producto SET foto = 'calibre-18x1-torcida.jpeg' WHERE id_mcr = 'MCR-18-1 3/4-NR-TO';
UPDATE red_producto SET foto = 'calibre-18x1-torcida.jpeg' WHERE id_mcr = 'MCR-18-1 3/4-NR-TR';
UPDATE red_producto SET foto = 'calibre-18x2-torcida.jpeg' WHERE id_mcr = 'MCR-18-2-TO';
UPDATE red_producto SET foto = 'calibre-18x2-torcida.jpeg' WHERE id_mcr = 'MCR-18-2-TR';
UPDATE red_producto SET foto = 'calibre-18x2-torcida.jpeg' WHERE id_mcr = 'MCR-18-2-NR-TO';
UPDATE red_producto SET foto = 'calibre-18x2-torcida.jpeg' WHERE id_mcr = 'MCR-18-2-NR-TR';
UPDATE red_producto SET foto = 'calibre-18x1-torcida.jpeg' WHERE id_mcr = 'MCR-18-2 1/8-TO';
UPDATE red_producto SET foto = 'calibre-18x1-torcida.jpeg' WHERE id_mcr = 'MCR-18-2 1/8-TR';
UPDATE red_producto SET foto = 'calibre-18x1-torcida.jpeg' WHERE id_mcr = 'MCR-18-2 1/4-TO';
UPDATE red_producto SET foto = 'calibre-18x1-torcida.jpeg' WHERE id_mcr = 'MCR-18-2 1/4-TR';
UPDATE red_producto SET foto = 'calibre-18x1-torcida.jpeg' WHERE id_mcr = 'MCR-18-2 1/2-TO';
UPDATE red_producto SET foto = 'calibre-18x1-torcida.jpeg' WHERE id_mcr = 'MCR-18-2 1/2-TR';
UPDATE red_producto SET foto = 'calibre-18x1-torcida.jpeg' WHERE id_mcr = 'MCR-18-3-TO';
UPDATE red_producto SET foto = 'calibre-18x1-torcida.jpeg' WHERE id_mcr = 'MCR-18-3-TR';
UPDATE red_producto SET foto = 'calibre-18x4-torcida.jpeg' WHERE id_mcr = 'MCR-18-4-TO';
UPDATE red_producto SET foto = 'calibre-18x4-torcida.jpeg' WHERE id_mcr = 'MCR-18-4-TR';
UPDATE red_producto SET foto = 'calibre-30x7-8-sq.jpeg' WHERE id_mcr = 'MCR-30-7/8-TO';
UPDATE red_producto SET foto = 'calibre-30x7-8-sq.jpeg' WHERE id_mcr = 'MCR-30-7/8-TR';
UPDATE red_producto SET foto = 'calibre-30x7-8-sq.jpeg' WHERE id_mcr = 'MCR-30-7/8-NR-T O';
UPDATE red_producto SET foto = 'calibre-30x7-8-sq.jpeg' WHERE id_mcr = 'MCR-30-7/8-NR-T R';
UPDATE red_producto SET foto = 'calibre-36x2-trenzada.jpeg' WHERE id_mcr = 'MCR-36-1-TO';
UPDATE red_producto SET foto = 'calibre-36x2-trenzada.jpeg' WHERE id_mcr = 'MCR-36-1-TR';
UPDATE red_producto SET foto = 'calibre-36x2-trenzada.jpeg' WHERE id_mcr = 'MCR-36-1-NR-TO';
UPDATE red_producto SET foto = 'calibre-36x2-trenzada.jpeg' WHERE id_mcr = 'MCR-36-1-NR-TR';
UPDATE red_producto SET foto = 'calibre-36x2-trenzada.jpeg' WHERE id_mcr = 'MCR-36-1 1/2-TO';
UPDATE red_producto SET foto = 'calibre-36x2-trenzada.jpeg' WHERE id_mcr = 'MCR-36-1 1/2-TR';
UPDATE red_producto SET foto = 'calibre-36x2-trenzada.jpeg' WHERE id_mcr = 'MCR-36-1 1/2-NR-TO';
UPDATE red_producto SET foto = 'calibre-36x2-trenzada.jpeg' WHERE id_mcr = 'MCR-36-1 1/2-NR-TR';
UPDATE red_producto SET foto = 'calibre-36x2-75-torcida.jpeg' WHERE id_mcr = 'MCR-36-1 3/4-TO';
UPDATE red_producto SET foto = 'calibre-36x2-75-torcida.jpeg' WHERE id_mcr = 'MCR-36-1 3/4-TR';
UPDATE red_producto SET foto = 'calibre-36x2-75-torcida.jpeg' WHERE id_mcr = 'MCR-36-1 3/4-NR-TO';
UPDATE red_producto SET foto = 'calibre-36x2-75-torcida.jpeg' WHERE id_mcr = 'MCR-36-1 3/4-NR-TR';
UPDATE red_producto SET foto = 'calibre-36x2-trenzada.jpeg' WHERE id_mcr = 'MCR-36-2-TO';
UPDATE red_producto SET foto = 'calibre-36x2-trenzada.jpeg' WHERE id_mcr = 'MCR-36-2-TR';
UPDATE red_producto SET foto = 'calibre-36x2-trenzada.jpeg' WHERE id_mcr = 'MCR-36-2-NR-TO';
UPDATE red_producto SET foto = 'calibre-36x2-trenzada.jpeg' WHERE id_mcr = 'MCR-36-2-NR-TR';
UPDATE red_producto SET foto = 'calibre-36x4-torcida.jpeg' WHERE id_mcr = 'MCR-36-4-TO';
UPDATE red_producto SET foto = 'calibre-36x4-torcida.jpeg' WHERE id_mcr = 'MCR-36-4-TR';
UPDATE red_producto SET foto = 'calibre-36x4-torcida.jpeg' WHERE id_mcr = 'MCR-36-4-NR-TO';
UPDATE red_producto SET foto = 'calibre-36x4-torcida.jpeg' WHERE id_mcr = 'MCR-36-4-NR-TR';
UPDATE red_producto SET foto = 'calibre-42x2-torcida.jpeg' WHERE id_mcr = 'MCR-42-1 3/4-TO';
UPDATE red_producto SET foto = 'calibre-42x2-torcida.jpeg' WHERE id_mcr = 'MCR-42-1 3/4-TR';
UPDATE red_producto SET foto = 'calibre-42x2-torcida.jpeg' WHERE id_mcr = 'MCR-42-1 3/4-NR-TO';
UPDATE red_producto SET foto = 'calibre-42x2-torcida.jpeg' WHERE id_mcr = 'MCR-42-1 3/4-NR-TR';
UPDATE red_producto SET foto = 'calibre-42x2-1-8-trenzada.jpeg' WHERE id_mcr = 'MCR-42-2 1/8-TO';
UPDATE red_producto SET foto = 'calibre-42x2-1-8-trenzada.jpeg' WHERE id_mcr = 'MCR-42-2 1/8-TR';
UPDATE red_producto SET foto = 'calibre-42x2-1-8-trenzada.jpeg' WHERE id_mcr = 'MCR-42-2 1/8-NR-TO';
UPDATE red_producto SET foto = 'calibre-42x2-1-8-trenzada.jpeg' WHERE id_mcr = 'MCR-42-2 1/8-NR-TR';
UPDATE red_producto SET foto = 'calibre-36x2-trenzada.jpeg' WHERE id_mcr = 'MCR-60-1-TO';
UPDATE red_producto SET foto = 'calibre-36x2-trenzada.jpeg' WHERE id_mcr = 'MCR-60-1-TR';
UPDATE red_producto SET foto = 'calibre-36x2-trenzada.jpeg' WHERE id_mcr = 'MCR-60-1-NR-TO';
UPDATE red_producto SET foto = 'calibre-36x2-trenzada.jpeg' WHERE id_mcr = 'MCR-60-1-NR-TR';
UPDATE red_producto SET foto = 'calibre-36x2-trenzada.jpeg' WHERE id_mcr = 'MCR-60-1 1/4-TO';
UPDATE red_producto SET foto = 'calibre-36x2-trenzada.jpeg' WHERE id_mcr = 'MCR-60-1 1/4-TR';
UPDATE red_producto SET foto = 'calibre-36x2-trenzada.jpeg' WHERE id_mcr = 'MCR-60-1 1/4-NR-TO';
UPDATE red_producto SET foto = 'calibre-36x2-trenzada.jpeg' WHERE id_mcr = 'MCR-60-1 1/4-NR-TR';
UPDATE red_producto SET foto = 'calibre-36x2-trenzada.jpeg' WHERE id_mcr = 'MCR-60-1 1/2-TO';
UPDATE red_producto SET foto = 'calibre-36x2-trenzada.jpeg' WHERE id_mcr = 'MCR-60-1 1/2-TR';
UPDATE red_producto SET foto = 'calibre-36x2-trenzada.jpeg' WHERE id_mcr = 'MCR-60-1 1/2-NR-TO';
UPDATE red_producto SET foto = 'calibre-36x2-trenzada.jpeg' WHERE id_mcr = 'MCR-60-1 1/2-NR-TR';
UPDATE red_producto SET foto = 'calibre-36x2-trenzada.jpeg' WHERE id_mcr = 'MCR-60-1 3/4-TO';
UPDATE red_producto SET foto = 'calibre-36x2-trenzada.jpeg' WHERE id_mcr = 'MCR-60-1 3/4-TR';
UPDATE red_producto SET foto = 'calibre-36x2-trenzada.jpeg' WHERE id_mcr = 'MCR-60-1 3/4-NR-TO';
UPDATE red_producto SET foto = 'calibre-36x2-trenzada.jpeg' WHERE id_mcr = 'MCR-60-1 3/4-NR-TR';
UPDATE red_producto SET foto = 'calibre-36x2-trenzada.jpeg' WHERE id_mcr = 'MCR-60-2-TO';
UPDATE red_producto SET foto = 'calibre-36x2-trenzada.jpeg' WHERE id_mcr = 'MCR-60-2-TR';
UPDATE red_producto SET foto = 'calibre-36x2-trenzada.jpeg' WHERE id_mcr = 'MCR-60-2-NR-TO';
UPDATE red_producto SET foto = 'calibre-36x2-trenzada.jpeg' WHERE id_mcr = 'MCR-60-2-NR-TR';
UPDATE red_producto SET foto = 'calibre-36x2-trenzada.jpeg' WHERE id_mcr = 'MCR-60-2 1/8-TO';
UPDATE red_producto SET foto = 'calibre-36x2-trenzada.jpeg' WHERE id_mcr = 'MCR-60-2 1/8-TR';
UPDATE red_producto SET foto = 'calibre-36x2-trenzada.jpeg' WHERE id_mcr = 'MCR-60-2 1/8-NR-TO';
UPDATE red_producto SET foto = 'calibre-36x2-trenzada.jpeg' WHERE id_mcr = 'MCR-60-2 1/8-NR-TR';
UPDATE red_producto SET foto = 'calibre-36x2-trenzada.jpeg' WHERE id_mcr = 'MCR-60-2 1/4-TO';
UPDATE red_producto SET foto = 'calibre-36x2-trenzada.jpeg' WHERE id_mcr = 'MCR-60-2 1/4-TR';
UPDATE red_producto SET foto = 'calibre-36x2-trenzada.jpeg' WHERE id_mcr = 'MCR-60-2 1/4-NR-TO';
UPDATE red_producto SET foto = 'calibre-36x2-trenzada.jpeg' WHERE id_mcr = 'MCR-60-2 1/4-NR-TR';
UPDATE red_producto SET foto = 'calibre-36x2-trenzada.jpeg' WHERE id_mcr = 'MCR-60-2 1/2-TO';
UPDATE red_producto SET foto = 'calibre-36x2-trenzada.jpeg' WHERE id_mcr = 'MCR-60-2 1/2-TR';
UPDATE red_producto SET foto = 'calibre-36x2-trenzada.jpeg' WHERE id_mcr = 'MCR-60-2 1/2-NR-TO';
UPDATE red_producto SET foto = 'calibre-36x2-trenzada.jpeg' WHERE id_mcr = 'MCR-60-2 1/2-NR-TR';
UPDATE red_producto SET foto = 'calibre-36x2-trenzada.jpeg' WHERE id_mcr = 'MCR-60-3-TO';
UPDATE red_producto SET foto = 'calibre-36x2-trenzada.jpeg' WHERE id_mcr = 'MCR-60-3-TR';
UPDATE red_producto SET foto = 'calibre-36x2-trenzada.jpeg' WHERE id_mcr = 'MCR-60-3-NR-TO';
UPDATE red_producto SET foto = 'calibre-36x2-trenzada.jpeg' WHERE id_mcr = 'MCR-60-3-NR-TR';
UPDATE red_producto SET foto = 'calibre-36x2-trenzada.jpeg' WHERE id_mcr = 'MCR-60-4-TO';
UPDATE red_producto SET foto = 'calibre-36x2-trenzada.jpeg' WHERE id_mcr = 'MCR-60-4-TR';
UPDATE red_producto SET foto = 'calibre-36x2-trenzada.jpeg' WHERE id_mcr = 'MCR-60-4-NR-TO';
UPDATE red_producto SET foto = 'calibre-36x2-trenzada.jpeg' WHERE id_mcr = 'MCR-60-4-NR-TR';